name: Test LLM Metaprogram

on:
  push:
    branches:    
      - main
  
jobs:
  Run:
    name: Run
    runs-on: ubuntu-supercharged

    permissions:
      contents: read
      id-token: 'write'

    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install OIDC Client from Core Package
        run: bun i @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: packages-${{ hashFiles('**/bun.lockb') }}
          restore-keys: packages-

      - id: Authenticate
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
            project_id: research-420207
            create_credentials_file: 'true'
            workload_identity_provider: projects/434258933066/locations/global/workloadIdentityPools/github/providers/turing
            service_account: github-actions@research-420207.iam.gserviceaccount.com

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Start tests
        run: bun src/main.mjs ctjlewis